//auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_CHANGE = 'LOGIN_CHANGE';
export const LOGOUT = 'LOGOUT';
export const LOADING = 'LOADING';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const ERROR_EDITING_PROFILE = 'ERROR_EDITING_PROFILE';
export const ERROR_EDITING_PASSWORD = 'ERROR_EDITING_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RESET_ERRORS = 'RESET_ERRORS';
export const CLEAN_MODIFIED = 'CLEAN_MODIFIED';
