export const LOADING_FACTORING = 'LOADING_FACTORING';
export const GET_FACTORING = 'GET_FACTORING';
export const EDIT_FACTORING = 'EDIT_FACTORING';
export const ERROR_EDiTING_FACTORING = 'ERROR_EDiTING_FACTORING';
export const RESET_ERRORS = 'RESET_ERRORS';
export const CLEAN_MODIFIED = 'CLEAN_MODIFIED';
