//notifications
export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOADING_NOTIFICATIONS = 'LOADING_NOTIFICATIONS';
export const MARK_ALL_READED = 'MARK_ALL_READED';
export const MARK_READED = 'MARK_READED';
