//trailer_maintenances
export const LOAD_TRAILER_MAINTENANCES = 'LOAD_TRAILER_MAINTENANCES';
export const LOADING_TRAILER_MAINTENANCES = 'LOADING_TRAILER_MAINTENANCES';
export const DELETE_TRAILER_MAINTENANCE = 'DELETE_TRAILER_MAINTENANCE';
export const ADD_TRAILER_MAINTENANCE = 'ADD_TRAILER_MAINTENANCE';

//trailers
export const LOAD_TRAILERS = 'LOAD_TRAILERS';
export const LOADING_TRAILERS = 'LOADING_TRAILERS';
export const DELETE_TRAILER = 'DELETE_TRAILER';
export const ADD_TRAILER = 'ADD_TRAILER';
export const GET_TRAILER = 'GET_TRAILER';
export const EDIT_TRAILER = 'EDIT_TRAILER';

//errors
export const ERROR_ADDING_TRAILER = 'ERROR_ADDING_TRAILER';
export const ERROR_EDiTING_TRAILER = 'ERROR_EDiTING_TRAILER';
export const RESET_ERRORS = 'RESET_ERRORS';
export const CLEAN_MODIFIED = 'CLEAN_MODIFIED';
